import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App1234',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/history">
            <button style={{ padding: '10px', margin: '10px', fontSize: '16px', backgroundColor: 'red', color: 'white' }}>
              View History
            </button>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}